### ISSUE TITLE
Remove unwanted text at the top of change password form

### ISSUE THREAD

**Issue by arpit3018** [mohitkh7/Easy-Learning#40]
![screenshot from 2018-12-30 00-48-52](https://user-images.githubusercontent.com/33262874/50549516-41c29b80-0c84-11e9-9ff9-190f282721ae.png)

**Comment by mohitkh7** [comment]
This issue is observed in all templates related to change and reset password. The content inside `{% block title %}` should have `<title>` tag around it.

How to address this issue -
In all the HTML template files inside `learn/templates/registration` enclose _reset password_ text with `<title>` tag`
